server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER}
          jwk-ser-uri: ${JWK_SER}
minio:
  host: ${MINIO_HOST}
  user: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}
keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  clientId: ${KEYCLOAK_CLIENT}
  clientSecret: ${KEYCLOAK_SECRET}
  username: ${KEYCLOAK_USER}
  password: ${KEYCLOAK_PASSWORD}