server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/main_db
    username: postgres_secret
    password: postgres_secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/online_gallery
          jwk-ser-uri: http://localhost:8000/realms/online_gallery/protocol/openid-connect/certs
minio:
  host: http://localhost:9000
  user: muser
  password: mpassword
keycloak:
  url: http://localhost:8000
  realm: online_gallery
  clientId: backend
  clientSecret: fXAvWBxMpzOGSYJvGRe4ZOOp3NFCwdSf
  username: backend@backend
  password: 123456789